<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_infokatalon.com_fa fa-facebook fa-fw fa-3x</name>
   <tag></tag>
   <elementGuidId>e5a9f618-3b27-45e3-ac2b-fa698cb5adff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-facebook.fa-fw.fa-3x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0ce6b91d-b2c7-49f5-8f1b-7108a3b5030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-facebook fa-fw fa-3x</value>
      <webElementGuid>afae42d4-85a4-4de1-a69f-8ab881f93918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 text-center&quot;]/ul[@class=&quot;list-inline&quot;]/li[1]/a[1]/i[@class=&quot;fa fa-facebook fa-fw fa-3x&quot;]</value>
      <webElementGuid>3a133feb-388d-4d9c-9279-58da1f4cef57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>8baead35-63fd-4822-a2c1-1881fb8a6609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
