name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Xvfb
      run: sudo apt-get install xvfb
      
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
    - name: Export DISPLAY environment variable
      run: export DISPLAY=:99

    - name: Permision to Katalon Folder
      run: chmod +x /home/runner/.katalon/8.6.6/Katalon_Studio_Engine_Linux_64-8.6.6/katalonc
      
    - name: Execute Katalon Studio
      run: /home/runner/.katalon/8.6.6/Katalon_Studio_Engine_Linux_64-8.6.6/katalonc -noSplash -runMode="console" -projectPath="/home/runner/work/Demo_UI/Demo_UI" -noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/smoke_test" -apiKey="${{ secrets.KATALON_API_KEY }}" --config -webui.autoUpdateDrivers=true
