name: Triggered from Repo A

on:
  repository_dispatch:
    types: [trigger-from-repo-a]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
      - name: Run your commands
        # Add your commands here
